
-- DROP TABLE IF EXISTS user_password_credentials CASCADE;
-- DROP TABLE IF EXISTS user_auth_identities CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;

-- 存放使用者資訊
CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,

    username VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',

    email VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE, -- 驗證可否發送 mail

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_username UNIQUE (username),

    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT ck_users_username_lowercase
        CHECK (username = LOWER(username)),

    CONSTRAINT ck_users_status
        CHECK (status IN ('active', 'suspended', 'deleted'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_public_id
    ON users(public_id);

-- 存放使用者授權認證表
CREATE TABLE IF NOT EXISTS user_auth_identities
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    provider VARCHAR(30) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_user_auth_identities_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_user_auth_identites_provider_subject
        UNIQUE (provider, provider_subject),

    CONSTRAINT uq_user_auth_identites_user_provider
        UNIQUE (user_id, provider),

    CONSTRAINT ck_user_auth_identities_provider
        CHECK (provider IN ('password', 'google', 'apple', 'github'))
);

CREATE INDEX IF NOT EXISTS idx_user_auth_identities_user_id
    ON user_auth_identities(user_id);


-- 存放密碼
CREATE TABLE IF NOT EXISTS user_password_credentials
(
    auth_identity_id BIGINT PRIMARY KEY,

    password_hash VARCHAR(255) NOT NULL,

    password_changed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    failed_attempts INTEGER NOT NULL DEFAULT 0,

    locked_until TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_user_password_credentials_identity
        FOREIGN KEY (auth_identity_id)
        REFERENCES user_auth_identities(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_user_password_credentials_failed_attempts
        CHECK (failed_attempts >= 0)
);

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    public_id UUID NOT NULL,
    owner_id BIGINT NOT NULL,

    name VARCHAR(100) NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',

    status VARCHAR(20) NOT NULL DEFAULT 'available',

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_items_owner
                             FOREIGN KEY (owner_id)
    REFERENCES users(id)
                         ON DELETE RESTRICT,

    CONSTRAINT ck_items_name_not_blank
    CHECK (CHAR_LENGTH(TRIM(name)) > 0),

    CONSTRAINT ck_items_status
    CHECK (status IN (
           'available',
           'unavailable',
           'archived'
                     )),

    CONSTRAINT ck_items_updated_at
    CHECK (updated_at >= created_at)
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_items_public_id
    ON items(public_id);

CREATE INDEX IF NOT EXISTS idx_items_owner_id_status
    ON items(owner_id, status);
